name: harvest_hub
description: "Harvest Hub - A farming game built with Flutter and Flame"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Game Engine
  flame: ^1.34.0
  flame_audio: ^2.11.12

  # UI & Fonts
  cupertino_icons: ^1.0.8
  ffi: ^2.1.5

  # Storage
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
